name: Auto Update

on:
  schedule:
    - cron: '0 17 * * *'
  push:
    paths:
      - 'main.py'
      - '.github/workflows/main.yml'

jobs:
  get-json:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' # specify the Python version you want to use

    - name: Install requests package
      run: pip install requests

    - name: Run main.py
      run: python main.py
      id: run_main

    - name: Commit and push
      if: steps.run_main.outcome == 'success'
      run: |
        git config --global user.name 'cymz6'
        git config --global user.email '95021138@qq.com'
        git add .
        git commit -m 'Automated update from main.py'
        git push
